const DATA_TYPE_BY_ID_DELETE_REQUEST = 'DATA_TYPE_BY_ID_DELETE_REQUEST';
const DATA_TYPE_BY_ID_DELETE_RESPONSE = 'DATA_TYPE_BY_ID_DELETE_RESPONSE';
const DATA_TYPE_BY_ID_DELETE_FAILURE = 'DATA_TYPE_BY_ID_DELETE_FAILURE';

const DATA_TYPE_BY_ID_GET_REQUEST = 'DATA_TYPE_BY_ID_GET_REQUEST';
const DATA_TYPE_BY_ID_GET_RESPONSE = 'DATA_TYPE_BY_ID_GET_RESPONSE';
const DATA_TYPE_BY_ID_GET_FAILURE = 'DATA_TYPE_BY_ID_GET_FAILURE';

const DATA_TYPE_BY_ID_PUT_REQUEST = 'DATA_TYPE_BY_ID_PUT_REQUEST';
const DATA_TYPE_BY_ID_PUT_RESPONSE = 'DATA_TYPE_BY_ID_PUT_RESPONSE';
const DATA_TYPE_BY_ID_PUT_FAILURE = 'DATA_TYPE_BY_ID_PUT_FAILURE';

const DATA_TYPE_GET_REQUEST = 'DATA_TYPE_GET_REQUEST';
const DATA_TYPE_GET_RESPONSE = 'DATA_TYPE_GET_RESPONSE';
const DATA_TYPE_GET_FAILURE = 'DATA_TYPE_GET_FAILURE';

const DATA_TYPE_POST_REQUEST = 'DATA_TYPE_POST_REQUEST';
const DATA_TYPE_POST_RESPONSE = 'DATA_TYPE_POST_RESPONSE';
const DATA_TYPE_POST_FAILURE = 'DATA_TYPE_POST_FAILURE';

const dataTypeByIdDeleteActionsTypes = [
  DATA_TYPE_BY_ID_DELETE_REQUEST,
  DATA_TYPE_BY_ID_DELETE_RESPONSE,
  DATA_TYPE_BY_ID_DELETE_FAILURE,
];

const dataTypeByIdGetActionsTypes = [
  DATA_TYPE_BY_ID_GET_REQUEST,
  DATA_TYPE_BY_ID_GET_RESPONSE,
  DATA_TYPE_BY_ID_GET_FAILURE,
];

const dataTypeByIdPutActionsTypes = [
  DATA_TYPE_BY_ID_PUT_REQUEST,
  DATA_TYPE_BY_ID_PUT_RESPONSE,
  DATA_TYPE_BY_ID_PUT_FAILURE,
];

const dataTypeGetActionsTypes = [
  DATA_TYPE_GET_REQUEST,
  DATA_TYPE_GET_RESPONSE,
  DATA_TYPE_GET_FAILURE,
];

const dataTypePostActionsTypes = [
  DATA_TYPE_POST_REQUEST,
  DATA_TYPE_POST_RESPONSE,
  DATA_TYPE_POST_FAILURE,
];


export const ActionsTypes =  {
  DATA_TYPE_BY_ID_DELETE_REQUEST,
  DATA_TYPE_BY_ID_DELETE_RESPONSE,
  DATA_TYPE_BY_ID_DELETE_FAILURE,
  dataTypeByIdDeleteActionsTypes,
  DATA_TYPE_BY_ID_GET_REQUEST,
  DATA_TYPE_BY_ID_GET_RESPONSE,
  DATA_TYPE_BY_ID_GET_FAILURE,
  dataTypeByIdGetActionsTypes,
  DATA_TYPE_BY_ID_PUT_REQUEST,
  DATA_TYPE_BY_ID_PUT_RESPONSE,
  DATA_TYPE_BY_ID_PUT_FAILURE,
  dataTypeByIdPutActionsTypes,
  DATA_TYPE_GET_REQUEST,
  DATA_TYPE_GET_RESPONSE,
  DATA_TYPE_GET_FAILURE,
  dataTypeGetActionsTypes,
  DATA_TYPE_POST_REQUEST,
  DATA_TYPE_POST_RESPONSE,
  DATA_TYPE_POST_FAILURE,
  dataTypePostActionsTypes
};
