const SWAGGER_GET_REQUEST = 'SWAGGER_GET_REQUEST';
const SWAGGER_GET_RESPONSE = 'SWAGGER_GET_RESPONSE';
const SWAGGER_GET_FAILURE = 'SWAGGER_GET_FAILURE';

const swaggerGetActionsTypes = [
  SWAGGER_GET_REQUEST,
  SWAGGER_GET_RESPONSE,
  SWAGGER_GET_FAILURE,
];


export const ActionsTypes =  {
  SWAGGER_GET_REQUEST,
  SWAGGER_GET_RESPONSE,
  SWAGGER_GET_FAILURE,
  swaggerGetActionsTypes
};
